# Example Configuration file for ldprotest

# If false, the application will not set secure flag on cookies or use https
# for endpoints on this server. Should be set to false for development
# environments only
usingHttps: true,

# Database connect string. It is strongly reccomended to use a stronger
# password in production environments.

mongoConnect: 'mongodb://ldprotest:ldprotest@localhost:27017/?serverSelectionTimeoutMS=3000'

userSessionConfig:
    # Seconds until a user session expires
    sessionExpiresSeconds: 604800
    # Seconds between key rotations of JWT RSA Keys
    tokenKeyRotateSeconds: 2592000
    # Seconds until a generated RSA key is deleted
    tokenKeyDeletionSeconds: 5184000
    # Seconds until JWT tokens expire. Note that this sets the limit on the time it takes for a user
    # lockout/ban to take effect because the application won't check the database until the token expires.
    # Setting this value too low, however, results in excessive database queries for user session data
    tokenExpiresSeconds: 900
