/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ldprotest;

import org.junit.Test;
import ldprotest.main.Main;

public class LockdownProtestTest {
    @Test public void testLdProtestCabnConstruct() {
        Main t = new Main();
    }
}
