/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ldprotest;

import ldprotest.main.Main;
import org.junit.jupiter.api.Test;

public class LockdownProtestTest {

    @Test
    public void testLdProtestCanConstruct() {
        Main t = new Main();
    }
}
